# Identificação
name_project: "VFI-Harmonization"
tbcomment: "init0_f1ep7f2ep13_norm2000_k8_bs256_alpha2.0-losspers-0.00005"
seed: 42

load_model: ""
model_source: "v2"

# Hiperparâmetros
lr: 0.0001
batch_size: 32
patch_size: 32
epochs: 100
alpha: 2.0
k_neighbors: 8

bval_max: 2000

# Pesos da Loss
loss_weights:
  l1: 1.0
  ssim: 1.0
  grad: 1.0
  res: 2.0
  wm: 2.0

curriculum:
  fase1: 25
  fase2: 50

# Caminhos (Cluster)
base_path: "/ix1/tibrahim/rmm270/DATA/DWIs/studies/all_bias"
csv_folder: "/ix1/tibrahim/rmm270/DATA/DWIs/studies/COORDS_DL_new"
checkpoint_dir: "checkpoints"